import React, { useState } from "react";
//this file sets how a imagechangebox behave
function imagechangeLayout({ imagechange, checkb }) {
  return (
    <div>
      <label>
        PizzaBase
        <input
          onChange={checkb}
          type="checkbox"
          defaultimagechangeed={true}
          checked={true}
          value="PizzaBase"
          name="PizzaBase"
          id="PizzaBase"
        />
      </label>
      <br></br>
      <label>
        Basecheese
        <input
          type="checkbox"
          value="Basecheese"
          defaultimagechangeed={imagechange.Basecheese}
          onChange={checkb}
        />
      </label>
      <br></br>
      <label>
        Basil
        <input
          type="checkbox"
          defaultimagechangeed={imagechange}
          value="Basil"
          onChange={checkb}
          name="Basil"
          id="Basil"
        />
      </label>
      <br></br>
      <label>
        Mushroom
        <input
          type="checkbox"
          defaultimagechangeed={imagechange}
          value="Mushroom"
          onChange={checkb}
          name="Mushroom"
          id="Mushroom"
        />
      </label>
      <br></br>
      <label>
        Olive
        <input
          type="checkbox"
          defaultimagechangeed={imagechange}
          value="Olive"
          onChange={checkb}
          name="Olive"
          id="Olive"
        />
      </label>
      <br></br>
      <label>
        Pineapple
        <input
          type="checkbox"
          defaultimagechangeed={imagechange}
          value="Pineapple"
          onChange={checkb}
          name="Pineapple"
          id="Pineapple"
        />
      </label>
      <br></br>
      <label>
        Tomato
        <input
          type="checkbox"
          defaultimagechangeed={imagechange}
          value="Tomato"
          onChange={checkb}
          name="Tomato"
          id="Tomato"
        />
      </label>
      <br></br>
    </div>
  );
}

export default imagechangeLayout;
