import React from "react";
//this file sets how a checkbox behave
function Inp({ changeIM, check }) {

  return (
    <div>
      <label>
        PizzaBase
        <input
          type="checkbox"
          defaultChecked={true}
          value="PizzaBase"
          name="PizzaBase"
          id="PizzaBase"
        />
      </label>
      <br></br>
      <label>
        Basecheese
        <input
          type="checkbox"
          value="Basecheese"
          defaultChecked={check}
          onClick={changeIM}
        />
      </label>
      <br></br>
      <label>
        Basil
        <input
          type="checkbox"
          defaultChecked={check}
          value="Basil"
          onClick={changeIM}
          name="Basil"
          id="Basil"
        />
      </label>
      <br></br>
      <label>
        Mushroom
        <input
          type="checkbox"
          defaultChecked={check}
          value="Mushroom"
          onClick={changeIM}
          name="Mushroom"
          id="Mushroom"
        />
      </label>
      <br></br>
      <label>
        Olive
        <input
          type="checkbox"
          defaultChecked={check}
          value="Olive"
          onClick={changeIM}
          name="Olive"
          id="Olive"
        />
      </label>
      <br></br>
      <label>
        Pineapple
        <input
          type="checkbox"
          defaultChecked={check}
          value="Pineapple"
          onClick={changeIM}
          name="Pineapple"
          id="Pineapple"
        />
      </label>
      <br></br>
      <label>
        Tomato
        <input
          type="checkbox"
          defaultChecked={check}
          value="Tomato"
          onClick={changeIM}
          name="Tomato"
          id="Tomato"
        />
      </label>
      <br></br>
    </div>
  );
}

export default Inp;
